[[plugins]] # utility for go
repo = "fatih/vim-go"
on_ft = ["go"]

[[plugins]] # markdown
repo = "tpope/vim-markdown"
on_ft = ["markdown"]
hook_source = """
    let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'go', 'javascript', 'vim']
    let g:markdown_syntax_conceal = 0
"""

[[plugins]]
repo = "dhruvasagar/vim-table-mode"
on_ft = ["markdown"]

[[plugins]] # syntax for toml
repo = "cespare/vim-toml"
on_ft = ["toml"]

[[plugins]] # autocomplete for python
repo = "zchee/deoplete-jedi"
on_ft = ["python"]
hook_post_source = """
    let g:deoplete#sources#jedi#show_docstring = 0
"""

[[plugins]] # auto pep8 indent
repo = "Vimjas/vim-python-pep8-indent"
on_ft = ["python"]

[[plugins]] # english
repo = "ujihisa/neco-look"
on_ft = ["markdown", "text"]

[[plugins]] # syntax for stylus
repo = "wavded/vim-stylus"
on_ft = ["stylus"]

[[plugins]] # linter runner for python
repo = "w0rp/ale"
on_ft = ["python", "javascript"]
hook_add = """
    let g:ale_sign_error = ">>"
    let g:ale_sign_warning = ">"
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_sign_column_always = 1
    let g:ale_lint_on_enter = 1
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'never'
    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 0
    let g:ale_open_list = 0
    let g:ale_keep_list_window_open = 0
    let g:ale_linters = {
    \   'python': ['flake8'],
    \   'javascript': ['eslint'],
    \}
    nmap [ale] <Nop>
    nmap <C-k> [ale]
    nmap <silent> [ale]<C-P> <Plug>(ale_previous)
    nmap <silent> [ale]<C-N> <Plug>(ale_next)
    nmap <silent> [ale]<C-l> :highlight<SPACE>ALEError<SPACE>ctermbg=DarkMagenta<CR>
    nmap <silent> [ale]<C-A> <Plug>(ale_toggle)
"""
